### PR TITLE
Add latency and NTP options

### PR DESCRIPTION
**Pull request by normen**
This PR adds latency and NTP server options for the plugin, allowing to sync network inputs with a fixed latency.

### CODE REVIEW

**Comment by normen** [comment]
> Is this an unstable API? It seems to be missing from the docs and not explicitly exported in their code.

I don't think its "unstable", its used in their own Decklink plugin as well as the externaly NDI plugin.

I am still working on the growing delay issue though. I already thought I fixed it completely but on my RTSP cameras it still grows (I let the plugin report latency changes in the pipieline, its not the pipeline). The good news is that with all these settings and when using the gst-plugin-ndi to stream NDI cameras to OBS it seems to be completely fixed.

I have a lengthy post to the issue tracker "in queue" which I composed when I thought these settings fixed it completely as this issue seems to pop up across many OBS plugins in one form or the other.

**Comment by normen** [comment]
> There usually is no easy way for clock sync between two different clocks. I know that in the past I had some code that compared network timestamps to current host clock. Over a time and filtering out jitter one could detect a clock drift between them and act accordingly. But I don't think I have it anymore and I'm too laze to tackle the issue again.
>
> Also feel free to mark this PR as draft so you can un-draft it when you feel happy with it.
>

Nah, syncing the cameras with NTP works great, I am also doing it in a standalone gstreamer app with the same settings. The issue is a "ghost latency" which seems to only occur in OBS, but not only with this plugin. It even happens when the appsink isn't synced, in that case the cams should simply deliver with network latency which they don't after a while.

Read: I still would like to have all these options in obs-gstreamer either way 😅

**Comment by TychoWerner** [comment]
It this someone @normen you are able to complete? I would love this functionallity

**Comment by normen** [comment]
IMO it is/was complete - by now theres new conflicts to resolve due to other changes though

**Comment by TychoWerner** [comment]
> IMO it is/was complete - by now theres new conflicts to resolve due to other changes though

Ah that's nice to hear. Is it now for @fzwoch to merge the final steps?
Wish to have SRT with SEI NTP syncing so this would be nice.

**Comment by lucaspontoexe** [comment]
The only breaking change I can see is in 9831483a290ef956ae88e4b0a63f9c601060ed5b, which split the `start_pipe()` function into `pipeline_restart()` and `pipeline_destroy()`

**Pull request closed without merging**
